src/Modules/FusionCore.Modules.InstallationManager/Controllers/ClientController.cs
using AutoMapper;
using FusionCore.Core.Extensions;
using FusionCore.Modules.InstallationManager.Data.Entities;
using FusionCore.Modules.InstallationManager.Interfaces;
using FusionCore.Modules.InstallationManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace FusionCore.Modules.InstallationManager.Controllers
{
    [Area("InstallationManager")]
    public class ClientController : FusionBaseController
    {
        private readonly IClientService _clientService;
        private readonly IDivisionService _divisionService;
        private readonly IEmployeeService _employeeService;
        private readonly IBuildingService _buildingService;
        private readonly IMapper _mapper;

        public ClientController(
            IClientService clientService,
            IDivisionService divisionService,
            IMapper mapper,
            IEmployeeService employeeService,
            IBuildingService buildingService)
        {
            _clientService = clientService;
            _divisionService = divisionService;
            _mapper = mapper;
            _employeeService = employeeService;
            _buildingService = buildingService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult DataTable(ClientDataTable model)
        {
            string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][data]"]
                .FirstOrDefault();
            string sortColumnDir = Request.Query["order[0][dir]"].FirstOrDefault() ?? "";
            string searchValue = Request.Query["search[value]"].FirstOrDefault();

            int pageSize = model.Length;
            int pageIndex = model.Start / model.Length;

            Expression<Func<Client, IComparable>> orderBy;

            switch (sortColumn)
            {
                case "name":
                    orderBy = x => x.Name;
                    break;
                case "contact":
                    orderBy = x => x.GetContact;
                    break;
                case "phonenumber":
                    orderBy = x => x.Phonenumber;
                    break;
                default:
                    orderBy = x => x.UpdatedOnUtc;
                    sortColumnDir = "desc";
                    break;
            }

            Expression<Func<Client, bool>> predicate = null;
            if (!string.IsNullOrEmpty(searchValue))
                predicate = x =>
                        x.Name.ToLower().Contains(searchValue.ToLower())
                        || x.Firstname.ToLower().Contains(searchValue.ToLower())
                        || x.Lastname.ToLower().Contains(searchValue.ToLower())
                        || x.Email.ToLower().Contains(searchValue.ToLower())
                    ;

            FusionCore.Models.Common.IPagedList<Client> clients = _clientService.GetAllClients(
                predicate,
                orderBy,
                sortColumnDir.Equals("asc", StringComparison.InvariantCultureIgnoreCase),
                pageIndex,
                pageSize);

            model.Data = _mapper.Map<List<ClientDataRow>>(clients);
            model.RecordsFiltered = clients.TotalCount;
            model.RecordsTotal = clients.TotalCount;
            return new JsonResult(model);
        }

        public JsonResult DataTableClientUsers(ClientUsersDataTable model)
        {
            string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][data]"]
                .FirstOrDefault();
            string sortColumnDir = Request.Query["order[0][dir]"].FirstOrDefault() ?? "";
            string searchValue = Request.Query["search[value]"].FirstOrDefault();

            int pageSize = model.Length;
            int pageIndex = model.Start / model.Length;

            Expression<Func<ClientUser, IComparable>> orderBy;

            switch (sortColumn)
            {
                case "name":
                    orderBy = x => x.Lastname;
                    break;
                default:
                    orderBy = x => x.UpdatedOnUtc;
                    sortColumnDir = "desc";
                    break;
            }

            Expression<Func<ClientUser, bool>> predicate = null;
            if (!string.IsNullOrEmpty(searchValue))
                predicate = x =>
                        x.Username.ToLower().Contains(searchValue.ToLower())
                        || x.Firstname.ToLower().Contains(searchValue.ToLower())
                        || x.Lastname.ToLower().Contains(searchValue.ToLower())
                    ;

            FusionCore.Models.Common.IPagedList<ClientUser> clients = _clientService.GetClientUserByClientId(model.ClientId,
                predicate,
                orderBy,
                sortColumnDir.Equals("asc", StringComparison.InvariantCultureIgnoreCase),
                pageIndex,
                pageSize);

            model.Data = _mapper.Map<List<ClientUserDataRow>>(clients);
            model.RecordsFiltered = clients.TotalCount;
            model.RecordsTotal = clients.TotalCount;
            return new JsonResult(model);
        }

        public IActionResult Get(int? id)
        {
            ClientPersistModel model = id.HasValue
                ? _mapper.Map<ClientPersistModel>(_clientService.GetClient(id.Value))
                : new ClientPersistModel();

            model.AvailableDivisions = _divisionService.GetAllDivisions(null, x => x.Name)
                .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();

            return View(model);
        }

        public IActionResult GetClientUser(int? id, int? clientId)
        {
            ClientUserPersistModel model = id.HasValue
                ? _mapper.Map<ClientUserPersistModel>(_clientService.GetClientUser(id.Value))
                : new ClientUserPersistModel();

            if (clientId.HasValue)
            {
                model.ClientId = clientId.Value;
            }

            if (model.ClientId > 0)
            {
                model.AvailableBuildings = _buildingService.GetAllBuildings(x => x.ClientId == model.ClientId, x => x.Name)
                    .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            }

            if (id.HasValue)
            {
                model.ClientUserRights = _mapper.Map<List<ClientUserRightModel>>(_clientService.GetClientUserRightsByClientUserId(id.Value).ToList());
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Persist(ClientPersistModel model)
        {
            if (ModelState.IsValid) return Json(_clientService.PersistClient(model));

            return Json(false);
        }

        [HttpPost]
        public IActionResult PersistClientUser(ClientUserPersistModel model)
        {
            if (!string.IsNullOrEmpty(model.Username))
            {
                FusionCore.Models.Common.IPagedList<Employee> existingUser = _employeeService.GetAllEmployees<Employee>(x => !string.IsNullOrEmpty(x.Username) &&
                    x.Username.Equals(model.Username, StringComparison.InvariantCultureIgnoreCase));
                if (existingUser.Any())
                {
                    ModelState.AddModelError("Existing User", "Er bestaat een werknemer met deze login");
                }
            }

            if (ModelState.IsValid) return Json(_clientService.PersistClientUser(model));

            return Json(new { result = false, errors = ModelState.Values.SelectMany(v => v.Errors.Select(x => x.ErrorMessage)) });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _clientService.DeleteClient(id);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteClientUser(int id)
        {
            await _clientService.DeleteClientUser(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult GetLocations(int id)
        {
            FusionCore.Models.Common.IPagedList<BuildingLocation> locations = _buildingService.GetAllBuildingLocations(id, orderBy: x => x.Name);
            return Json(locations.Select(x => new { x.Id, x.Name }));
        }
    }
}

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Client/Get.cshtml
@using FusionCore.Modules.InstallationManager.Models
@model FusionCore.Modules.InstallationManager.Models.ClientPersistModel
@{
	Layout = null;
}
<form asp-action="Persist">
<input type="hidden" asp-for="Id"/>
<div class="modal-body">
<div class="row">
<div class="col-sm-8">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-external fa-reorder"></i>
			<div class="mobile_text">Opdrachtgevers informatie</div>
			<div class="panel-tools big">
				<a class="btn btn-lg btn-link panel-collapse collapses" href="#">
				</a>
				<a class="btn btn-lg btn-link panel-expand" href="#">
					<i class="fa icon-resize-full"></i>
				</a>
			</div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-12">
					<div id="panel_edit_account" class="tab-pane">
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">Opdrachtgever</label>
									<input type="text" placeholder="Novi Media" class="form-control" asp-for="Name"/>
								</div>
								<label class="control-label">Divisies</label>
								@for (var i = 0; i < Model.ClientDivisions.Count; i++)
								{
									<div class="form-group">
										<span class="input-icon dropdown_space_page button-backspace-NM">
											<select class="form-control button-backspace-NM" asp-for="@Model.ClientDivisions[i].DivisionId" asp-items="@Model.AvailableDivisions">
												<option value="">Selecteer een divisie</option>
											</select>
											<i class="fa fa-building"></i>
										</span>
										<a href="#" class="btn btn-bricky tooltips button-backspace-stack-NM js-division-remove" data-placement="top" data-original-title="Remove">
											<i class="fa fa-times fa fa-white"></i>
										</a>
									</div>
								}
								@{
									Model.ClientDivisions.Add(new ClientDivisionModel());
								}
								<div class="form-group">
									<span class="input-icon dropdown_space_page button-backspace-NM">
										<select class="form-control button-backspace-NM" asp-for="@Model.ClientDivisions[Model.ClientDivisions.Count - 1].DivisionId" asp-items="@Model.AvailableDivisions">
											<option value="">Selecteer een divisie</option>
										</select>
										<i class="fa fa-building"></i>
									</span>
									<a href="#" class="btn btn-teal tooltips button-backspace-stack-NM js-division-add" data-placement="top" data-original-title="Add">
										<i class="fa fa-plus fa fa-white"></i>
									</a>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="space_white"></div>
								<h4>Contactpersoon</h4>
								<hr />
								<div class="form-group">
									<label class="control-label">Naam</label>
									<input type="text" placeholder="Peter" class="form-control" asp-for="Firstname"/>
								</div>
								<div class="form-group">
									<label class="control-label">tussenvoegsel</label>
									<input type="text" placeholder="de" class="form-control" asp-for="Middlename"/>
								</div>
								<div class="form-group">
									<label class="control-label">Achternaam</label>
									<input type="text" placeholder="Vries" class="form-control" asp-for="Lastname">
								</div>
								<h4>Contact informatie</h4>
								<hr />
								<div class="form-group">
									<label class="control-label">Email</label>
									<span class="input-icon">
										<input type="text" placeholder="info@novimedia.nl" class="form-control" asp-for="Email"/>
										<i class="fa fa-envelope-square"></i>
									</span>
								</div>
								<div class="form-group">
									<label class="control-label">Telefoon</label>
									<span class="input-icon">
										<input type="text" placeholder="03055669988" class="form-control" asp-for="Phonenumber"/>
										<i class="fa fa-phone-square"></i>
									</span>
								</div>
								<div class="form-group">
									<label class="control-label">Mobiel</label>
									<span class="input-icon">
										<input type="text" placeholder="0622008899" class="form-control" asp-for="Mobilenumber"/>
										<i class="fa clip-mobile"></i>
									</span>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="space_white"></div>
								<h4>Adres gegevens</h4>
								<hr />
								<div class="form-group">
									<label class="control-label">Adres</label>
									<input type="text" placeholder="Duizendknooplaan 19" class="form-control" asp-for="Address"/>
								</div>
								<div class="row">
									<div class="col-md-3">
										<div class="form-group">
											<label class="control-label">Postcode</label>
											<input class="form-control" placeholder="12345" type="text" asp-for="PostalCode"/>
										</div>
									</div>
									<div class="col-md-9">
										<div class="form-group">
											<label class="control-label">Woonplaats</label>
											<input class="form-control tooltips" placeholder="London (UK)" type="text" title="" asp-for="City"/>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label">Land</label>
									<input type="text" placeholder="the Netherlands" class="form-control" asp-for="Country"/>
								</div>
								<h4>Overig</h4>
								<hr />
								<div class="form-group">
									<label class="control-label">Website</label>
									<span class="input-icon">
										<input type="text" placeholder="www.novimedia.nl" class="form-control" asp-for="Website"/>
										<i class="fa clip-globe"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-sm-4">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-external fa-reorder"></i>
			<div class="mobile_text">Pagina instellingen</div>
			<div class="panel-tools big">
				<a class="btn btn-lg btn-link panel-collapse collapses" href="#">
				</a>
				<a class="btn btn-lg btn-link panel-expand" href="#">
					<i class="fa icon-resize-full"></i>
				</a>
			</div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-12">
					<input type="checkbox" data-toggle="toggle" data-onstyle="teal" asp-for="Active">&nbsp;&nbsp; Activiteit
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-sm-4">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-external fa-reorder"></i>
			<div class="mobile_text">Bedrijfs Logo</div>
			<div class="panel-tools big">
				<a class="btn btn-lg btn-link panel-collapse collapses" href="#"></a>
				<a class="btn btn-lg btn-link panel-expand" href="#">
					<i class="fa icon-resize-full"></i>
				</a>
			</div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="form-group">
							<div class="col-sm-12">
								<fileupload
									asp-id="CompanyLogoPictureId"
									asp-value="@Model.CompanyLogoPictureId">
								</fileupload>
							</div>
						</div>
						<div class="col-sm-12 margin-top">
							<div class="alert alert-block alert-info fade in">
								<button data-dismiss="alert" class="close" type="button">&times;</button>
								<h4 class="alert-heading"><i class="fa fa-info-circle"></i> Beeld formaat</h4>
								<p>Formaat van deze afbeelding is maximaal 75 pixels hoog</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-sm-4">
	@if (Model.Id.HasValue)
	{
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-external fa-reorder"></i>
				<div class="mobile_text">Gebruikers</div>
				<div class="panel-tools big">
					<a class="btn btn-lg btn-link panel-collapse collapses" href="#"> </a>
					<a class="btn btn-lg btn-link panel-refresh js-refresh" data-id="#clientusers" href="#"><i class="fa fa-refresh"></i></a>
					<a class="btn btn-lg btn-link panel-expand" href="#">
						<i class="fa icon-resize-full"></i>
					</a>
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-bordered table-full-width" id="clientusers">
					<thead>
					<tr>
						<th>Naam</th>
						<th class="center">Edit</th>
					</tr>
					</thead>
				</table>
				<hr class="no-margin-top">
				<span class="pull-right">
					<a class="btn btn-primary js-popupuser-modal" href="#" data-class="" data-title="Nieuwe gebruiker" data-url="@Url.Action("GetClientUser", new {clientId = Model.Id})"><i class="fa fa-plus"></i> toevoegen</a>
				</span>
			</div>
		</div>
	}
</div>
</div>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Terug</button>
	<button type="submit" class="btn btn-primary">Opslaan</button>
</div>
</form>
<script>
	jQuery(document).ready(function() {
		$('#clientusers').DataTable({
			'stateSave': true,
			"processing": true,
			"serverSide": true,
			"filter": false,
			"orderMulti": false,
			"ajax": "@Url.Action("DataTableClientUsers", new {clientId = Model.Id})",
			"columns": [
				{ "data": "name" },
				{ "data": "buttons" }
			],
			"columnDefs": [
				{
					"render": function(data, type, row) {
						var returnValue = "";
						var modalProperties = " data-title=\"" +
							row.name +
							"\" data-url=\"@Url.Action("GetClientUser")/" +
							row.id +
							"\" data-class=\"\"";
						var deleteUrl = "@Url.Action("DeleteClientUser")/" + row.id;
						returnValue += "<div class=\"visible-md visible-lg hidden-sm hidden-xs\">\n";
						returnValue +=
							"<a href=\"#panel-gebruiker-edit\" class=\"btn btn-teal tooltips js-popup-modal-custom\" " +
							modalProperties +
							" data-placement=\"top\" data-original-title=\"Edit\"><i class=\"fa fa-edit\"></i></a>\n";
						returnValue +=
							"<a href=\"" +
							deleteUrl +
							"\" class=\"btn btn-bricky tooltips js-modal-delete\" data-placement=\"top\" data-original-title=\"Remove\"><i class=\"fa fa-times fa fa-white\"></i></a>\n";
						returnValue += "</div>\n";
						returnValue += "<div class=\"visible-xs visible-sm hidden-md hidden-lg\">\n";
						returnValue += "<div class=\"btn-group\">\n";
						returnValue +=
							"<a class=\"btn btn-primary dropdown-toggle btn-sm\" data-toggle=\"dropdown\" href=\"#\"><i class=\"fa fa-cog\"></i> <span class=\"caret\"></span></a>\n";
						returnValue += "<ul role=\"menu\" class=\"dropdown-menu pull-right\">\n";
						returnValue +=
							"<li role=\"presentation\"><a role=\"menuitem\" href=\"#\" class=\"js-popup-modal-custom\" " +
							modalProperties +
							"><i class=\"fa fa-edit\"></i> Edit</a></li>\n";
						returnValue +=
							"<li role=\"presentation\"><a role=\"menuitem\" href=\"" +
							deleteUrl +
							"\" class=\"js-modal-delete\"><i class=\"fa fa-times\"></i> Remove</a></li>\n";
						returnValue += "</ul>\n";
						returnValue += "</div>\n";
						returnValue += "</div>\n";

						return returnValue;
					},
					className: "center",
					"targets": 1,
					"orderable": false
				}
			]
		});
	});
</script>

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Client/GetClientUser.cshtml
@using FusionCore.Modules.InstallationManager.Models
@model FusionCore.Modules.InstallationManager.Models.ClientUserPersistModel
@{
	Layout = null;
}
<form asp-action="PersistClientUser">
	<input type="hidden" asp-for="Id" />
	<input type="hidden" asp-for="ClientId" />
	<div class="modal-body">
		<div class="row">
			<div class="col-sm-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-external fa-reorder"></i>
						<div class="mobile_text">Gebruikers informatie</div>
						<div class="panel-tools big">
							<a class="btn btn-lg btn-link panel-collapse collapses" href="#"></a>
							<a class="btn btn-lg btn-link panel-expand" href="#">
								<i class="fa icon-resize-full"></i>
							</a>
						</div>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-12">
								<div id="panel_edit_account" class="tab-pane">
									<div class="row">
										<div class="col-sm-12">
											<div class="space_white"></div>
											<div class="form-group">
												<label class="control-label">Naam</label>
												<input type="text" placeholder="Peter" class="form-control" asp-for="Firstname">
											</div>
											<div class="form-group">
												<label class="control-label">tussenvoegsel</label>
												<input type="text" placeholder="de" class="form-control" asp-for="Middlename">
											</div>
											<div class="form-group">
												<label class="control-label">Achternaam</label>
												<input type="text" placeholder="Vries" class="form-control" asp-for="Lastname">
											</div>
											<div class="space_white"></div>
											<h4>Login informatie</h4>
											<hr />
											<div class="form-group">
												<label class="control-label">Gebruikersnaam</label>
												<span class="input-icon">
													<input type="text" placeholder="gebruikersnaam" class="form-control" asp-for="Username">
													<i class="fa fa-user"></i>
												</span>
											</div>
											<div class="form-group">
												<label class="control-label">Wachtwoord</label>
												<span class="input-icon">
													<input type="password" placeholder="wachtwoord" class="form-control" asp-for="Password">
													<i class="fa fa-lock"></i>
												</span>
											</div>
											<div class="form-group">
												<label class="control-label">Wachtwoord controle</label>
												<span class="input-icon">
													<input type="password" placeholder="wachtwoord controle" class="form-control" asp-for="PasswordControle">
													<i class="fa fa-lock"></i>
												</span>
											</div>
											<hr />
											<div class="row">
												<div class="col-md-12">
													<input type="checkbox" asp-for="Active" data-toggle="toggle" data-onstyle="teal">&nbsp;&nbsp; Activiteit
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row" @Html.Raw(!Model.Id.HasValue || Model.Id == 0 ? "style=\"display:none;\"" : "")>
			<div class="col-sm-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-external fa-reorder"></i>
						<div class="mobile_text">Bestandstoegang</div>
						<div class="panel-tools big">
							<a class="btn btn-lg btn-link panel-collapse collapses" href="#"></a>
							<a class="btn btn-lg btn-link panel-expand" href="#">
								<i class="fa icon-resize-full"></i>
							</a>
						</div>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-12" id="accordion">
									@{
										Model.ClientUserRights.Add(new ClientUserRightModel());
									}
									@for (var i = 0; i < Model.ClientUserRights.Count; i++)
									{
										var right = Model.ClientUserRights[i];
										var isLastItem = i == (Model.ClientUserRights.Count - 1);
										var value = "collapse" + new Random().Next(0, 99999);
										if (isLastItem)
										{
											@:<div class="js-dummy" data-id="@value" style="display:none">
											}
											<div class="panel-group">
												<div class="panel panel-default">
													<div class="panel-heading padding-left-small">
														<a data-toggle="collapse" data-parent="#accordion" href="#@value" class="link-collapse text-resp"><i class="fa fa-arrow-down"></i> @Model.ClientName - Alle bestanden</a>
														<a href="#" class="btn btn-bricky tooltips pull-right js-clientuserright-delete" style="margin-right: -14px; margin-top: -9px;" data-placement="top" data-original-title="Remove">
															<i class="fa fa-times fa fa-white"></i>
														</a>
													</div>
													<div id="@value" class="panel-collapse collapse">
														<div class="panel-body">
															<div class="col-md-12">
																<div class="form-group">
																	<div class="row">
																		<div class="col-md-12">
																			<label class="control-label">Bedrijf</label>
																		</div>
																		<div class="col-md-7">
																			<input type="text" placeholder="@Model.ClientName" class="form-control" id="Model.ClientName" name="Model.ClientName" disabled>
																		</div>
																		<div class="col-md-5">
																			<input name="ClientUserRights[@i].AllBuildings" type="checkbox" value="true" @Html.Raw(!right.BuildingId.HasValue ? "checked" : "") @Html.Raw(!isLastItem ? "data-toggle=\"toggle\" data-size=\"normal\"" : "") class="js-chk-allcompany @(isLastItem ? "js-dummy-input" : "") @(isLastItem ? "js-dummy-checkbox" : "") ignore"/>&nbsp;&nbsp;&nbsp;Alle bestanden
																			<input name="ClientUserRights[@i].AllBuildings" type="hidden" value="false" />
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="row">
																		<div class="col-md-12">
																			<label class="control-label">Gebouw</label>
																		</div>
																		<div class="col-md-7">
																			<span class="input-icon dropdown_space_page">
																				<select asp-for="@Model.ClientUserRights[i].BuildingId" class="form-control js-building @(isLastItem ? "js-dummy-input":"")" data-url="@Url.Action("GetLocations", "Client")">
																					<option value="">Selecteer een gebouw</option>
																					@foreach (var item in Model.AvailableBuildings)
																					{
																						<option value="@item.Value">@item.Text</option>
																					}
																				</select>
																				<i class="fa fa-building"></i>
																				<input type="hidden" asp-for="@Model.ClientUserRights[i].Id" class=" @(isLastItem ? "js-dummy-input":"")"/>
																			</span>
																		</div>
																		<div class="col-md-5">
																			<input name="ClientUserRights[@i].AllLocations" type="checkbox" value="true" @Html.Raw(!right.BuildingLocationId.HasValue ? "checked" : "") @Html.Raw(!isLastItem ? "data-toggle=\"toggle\" data-size=\"normal\"" : "") class="js-chk-allbuilding @(isLastItem ? "js-dummy-input" : "") @(isLastItem ? "js-dummy-checkbox" : "") ignore"/>&nbsp;&nbsp;&nbsp;Alle bestanden
																			<input name="ClientUserRights[@i].AllLocations" type="hidden" value="false" />
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="row">
																		<div class="col-md-12">
																			<label class="control-label">Locatie</label>
																		</div>
																		<div class="col-md-7">
																			<span class="input-icon dropdown_space_page">
																				<select asp-for="@Model.ClientUserRights[i].BuildingLocationId" class="form-control js-location @(isLastItem ? "js-dummy-input":"")" data-oldvalue="@Model.ClientUserRights[i].BuildingLocationId">
																					<option value="">Selecteer een locatie</option>

																				</select>
																				<i class="fa fa-map-marker"></i>
																			</span>
																		</div>
																		<div class="col-md-5"></div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											if (isLastItem)
											{
											@:</div>
										}
									}
							</div>
						</div>
						<hr class="no-margin-top">
						<div class="row">
							<div class="col-md-6">
							</div>
							<div class="col-md-6">
								<span class="pull-right">
									<a class="btn btn-primary" href="#" id="js-addClientUserRight"><i class="fa fa-plus"></i> toevoegen</a>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Terug</button>
		<button type="submit" class="btn btn-primary">Opslaan</button>
	</div>
</form>