src/Modules/FusionCore.Modules.InstallationManager/Controllers/ControleController.cs
using AutoMapper;
using FusionCore.Core.Enums;
using FusionCore.Core.Exceptions;
using FusionCore.Core.Extensions;
using FusionCore.Core.Helpers;
using FusionCore.Modules.InstallationManager.Data.Entities;
using FusionCore.Modules.InstallationManager.Data.Enums;
using FusionCore.Modules.InstallationManager.Interfaces;
using FusionCore.Modules.InstallationManager.Models;
using FusionCore.Modules.InstallationManager.Models.Shared;
using FusionCore.Modules.InstallationManager.Services;
using FusionCore.Services.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace FusionCore.Modules.InstallationManager.Controllers
{
    [Area("InstallationManager")]
    public class ControleController : FusionBaseController
    {
        private readonly IPlanningService _planningService;
        private readonly IAssetService _assetService;
        private readonly IAssetFileService _assetFileService;
        private readonly IMapper _mapper;

        public ControleController(
            IPlanningService planningService,
            IMapper mapper,
            IAssetService assetService,
            IAssetFileService assetFileService)
        {
            _planningService = planningService;
            _mapper = mapper;
            _assetService = assetService;
            _assetFileService = assetFileService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> FileUpload(IFormFile file_data, int fileType, int planningId, string description, int historyTypeId)
        {
            try
            {
                if (file_data != null)
                {
                    var planning = await _planningService.GetPlanningAsync(planningId);
                    if (planning == null) throw new Exception($"Planning not found with id {planningId}");
                    if (file_data.Length <= 0) throw new FusionCoreException("File is empty");

                    var fileName = FileService.RemoveInvalidCharacters(file_data);
                    using (var ms = new MemoryStream())
                    {
                        await file_data.CopyToAsync(ms);
                        var fileBinary = ms.ToArray();

                        var assetFile = new AssetFile
                        {
                            AssetId = planning.AssetId.GetValueOrDefault(),
                            Title = fileName,
                            Description = description,
                            FileType = (FileType)fileType,
                            CreatedOnUtc = DateTime.UtcNow,
                            UpdatedOnUtc = DateTime.UtcNow,
                            PlanningId = planningId
                        };
                        await _assetService.CreateAssetFileAsync(assetFile);


                        var assetFileBinary = new AssetFileBinary()
                        {
                            AssetFileId = assetFile.Id,
                            File = fileBinary
                        };
                        await _assetFileService.InsertAssetFileBinaryAsync(assetFileBinary);

                        var result = await _planningService.SaveFileToHistory(null, planningId, assetFile, (DynamicFieldType)historyTypeId);
                        if (result.HasValue)
                        {
                            return Ok(new { id = result.Value, file = Convert.ToBase64String(fileBinary), description = (description ?? ""), createdon = assetFile.CreatedOnUtc.ConvertToUserTime().ToString("dd-MM-yyyy - HH:mm"), assetFile.Title, append = true });
                        }
                    }
                }
                return BadRequest();
            }
            catch (Exception er)
            {
                return BadRequest($"Fout tijdens uploaden file_data: {er.Message}");
            }
        }

        public JsonResult DataTable(ControleDataTable model)
        {
            var sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][data]"]
                .FirstOrDefault();
            var sortColumnDir = Request.Query["order[0][dir]"].FirstOrDefault() ?? "";
            var searchValue = Request.Query["search[value]"].FirstOrDefault();

            var pageSize = model.Length;
            var pageIndex = model.Start / model.Length;

            Expression<Func<Planning, IComparable>> orderBy;

            switch (sortColumn)
            {
                case "date":
                    orderBy = x => x.StartDate;
                    break;
                case "offernumber":
                    orderBy = x => x.OfferNumber;
                    break;
                case "employee":
                    orderBy = x => x.MainEmployee.Lastname;
                    break;
                case "building":
                    orderBy = x => x.Building.Name;
                    break;
                case "asset":
                    orderBy = x => x.Asset.Name;
                    break;
                case "activity":
                    orderBy = x => x.AssetActivity.Name;
                    break;
                case "status":
                    orderBy = x => x.StatusId;
                    break;
                default:
                    orderBy = x => x.StartDate;
                    sortColumnDir = "desc";
                    break;
            }

            Expression<Func<Planning, bool>> predicate = null;
            if (!string.IsNullOrEmpty(searchValue))
            {
                predicate = x =>
                        x.StatusId == (int)PlanningStatus.TechnicallyReady &&
                        (x.Asset.Name.ToLower().Contains(searchValue.ToLower())
                         || x.OfferNumber.ToLower().Contains(searchValue.ToLower())
                         || x.Building.Name.ToLower().Contains(searchValue.ToLower())
                         || x.AssetActivity.Name.ToLower().Contains(searchValue.ToLower())
                         || x.MainEmployee.Lastname.ToLower().Contains(searchValue.ToLower())
                         || x.MainEmployee.Firstname.ToLower().Contains(searchValue.ToLower())
                         || x.Client.Name.ToLower().Contains(searchValue.ToLower()))
                    ;
            }
            else
            {
                predicate = x =>
                    x.StatusId == (int)PlanningStatus.TechnicallyReady;
            }

            var plannings = _planningService.GetAllPlannings(
                predicate,
                orderBy,
                sortColumnDir.Equals("asc", StringComparison.InvariantCultureIgnoreCase),
                pageIndex,
                pageSize,
                true);

            model.Data = _mapper.Map<List<ControleDataRow>>(plannings);
            model.RecordsFiltered = plannings.TotalCount;
            model.RecordsTotal = plannings.TotalCount;
            return new JsonResult(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var planning = await _planningService.GetPlanningAsync(id);

            planning.Status = PlanningStatus.Deleted;
            _planningService.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> StatusUpdate(int id, int status)
        {
            var planning = await _planningService.GetPlanningAsync(id);

            if (status == (int)PlanningStatus.Complete)
            {
                await _planningService.GenerateRapportage(planning);
                planning.Status = PlanningStatus.Complete;
                _planningService.SaveChanges();
                _planningService.SaveLatestValues(planning);
            }
            return Content("");
        }

        public async Task<IActionResult> Get(int? id)
        {
            var model = id.HasValue ? _mapper.Map<ControlePersistModel>(await _planningService.GetPlanningAsync(id.Value)) : new ControlePersistModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromBody] PlanningSaveModel model)
        {
            var planning = await _planningService.GetPlanningAsync(Convert.ToInt32(model.PlanningId));
            if (planning == null) throw new Exception($"Planning not found with id {model.PlanningId}");

            PlanningMapper.ProcessSaveModel(model, planning, _planningService);

            await _planningService.UpdatePlanningAsync(planning);
            await _assetService.SaveLatestValues(planning);

            return Json(true);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult SaveAssetActivityHistoryTitle(int? pk, string value)
        {
            if (pk == 0) pk = null;
            var item = _assetService.GetAssetActivityHistoryById(pk.GetValueOrDefault());
            item.Name = value;
            _assetService.SaveChanges();
            return Json(true);
        }

        public async Task<IActionResult> FileDownloadAsync(int id)
        {
            var history = _assetService.GetAssetActivityHistoryById(id);
            if (history?.AssetFile != null)
            {
                var fileDownloadName = history.AssetFile.Title;
                var extension = Path.GetExtension(fileDownloadName);
                if (string.IsNullOrEmpty(extension) || !FileHelper.IsKnownType(extension))
                {
                    fileDownloadName = fileDownloadName + ".pdf";
                }
                var cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = fileDownloadName,
                    Inline = true,
                };

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Controle/Index.cshtml
@using FusionCore.Modules.InstallationManager.Data.Enums
@{
    ViewData["Title"] = "Installatie controle overzicht";
    Layout = "~/Views/Shared/_layout.cshtml";
}

@section Head {
    <link href="~/assets/libs/select2/dist/css/select2.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/datatables/media/css/dataTables.bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/summernote/dist/summernote.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/bootstrap-social/bootstrap-social.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" asp-append-version="true" />

    <style>

        .af_range.af_range_ok {
            background: #92d050;
            color: #000000;
        }

        .af_range.af_range_outside {
            background: #ffc000;
            color: #000000;
        }

        .af_hv.af_hv_1,
        .af_hv.af_hv_2 {
            background: rgb(83, 142, 213);
            color: #000000;
        }

        .af_hv.af_hv_3,
        .af_hv.af_hv_4 {
            background: rgb(146, 208, 80);
            color: #000000;
        }

        .af_hv.af_hv_5 {
            background: rgb(255, 192, 0);
            color: #000000;
        }

        .af_hv.af_hv_6 {
            background: rgb(255, 0, 0);
            color: #000000;
        }

        .af_tvrtav.af_tvrtav_1 {
            background: rgb(146, 208, 80);
            color: #000000;
        }


        .af_tvrtav.af_tvrtav_2 {
            background: rgb(255, 192, 0);
            color: #000000;
        }


        .af_tvrtav.af_tvrtav_3 {
            background: rgb(255, 0, 0);
            color: #000000;
        }
    </style>
}

@section Scripts {
    <script src="~/assets/libs/moment/min/moment.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-maxlength/src/bootstrap-maxlength.js" asp-append-version="true"></script>
    <script src="~/assets/libs/autosize/dist/autosize.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/select2/dist/js/select2.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.maskedinput/dist/jquery.maskedinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery-maskmoney/dist/jquery.maskMoney.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-daterangepicker/daterangepicker.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.js" asp-append-version="true"></script>
    <script src="~/assets/libs/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.tagsinput/src/jquery.tagsinput.js" asp-append-version="true"></script>
    <script src="~/assets/libs/summernote/dist/summernote.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/ckeditor/ckeditor.js" asp-append-version="true"></script>
    <script src="~/assets/libs/ckeditor/adapters/jquery.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.pulsate/jquery.pulsate.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootbox.js/bootbox.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery-mockjax/dist/jquery.mockjax.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/datatables/media/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/datatables/media/js/dataTables.bootstrap.js" asp-append-version="true"></script>
    <script src="~/assets/libs/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js" asp-append-version="true"></script>
    <script src="~/assets/js/table-data.js" asp-append-version="true"></script>
    <script src="~/assets/js/pages-user-profile.js" asp-append-version="true"></script>
    <script src="~/assets/js/form-elements.js" asp-append-version="true"></script>
    <script src="@Url.Action("GetJs", "Common", new { filename="Assets.signature_pad.js", assemblyName = "FusionCore.Modules.InstallationManager", area = "" })" asp-append-version="true"></script>
    <script>
		jQuery(document).ready(function() {

            $("body").on("click",
                ".js-statuschange",
                function (e) {
                    e.preventDefault();
                    var url = $(this).attr('href');
                    $.ajax({
                        url: url
                    }).then(function () {
                        $("#controle").DataTable().ajax.reload();
                    });
                })
                .on('click', '.js-rotate-image', function (e) {
                    e.preventDefault();
                    var $this = $(this);
                    var id = $this.data('id');
                    var planningId = $this.data('planning');
                    var kind = $this.data('kind');
                    $.ajax({
                        url: '@Url.Action("RotateImage", "Controle")/' + id + '?kind=' + kind + 
						'&planningId=' + planningId,
                        type: 'POST',
						beforeSend: function (xhr) {
							xhr.setRequestHeader("RequestVerificationToken",
								$('input:hidden[name="__RequestVerificationToken"]').val());
						},
                    }).then(function (data) {
                        if (data === 'reload') {
                            var $img = $('#img' + id);
                            var src = $img.attr('src').split("?")[0];
                            var d = new Date();
                            $img.attr("src", src + '?' + d.getTime());
                        }   

                    });
                });

			$('#controle').DataTable({
				'stateSave': true,
				"order": [[0, "desc"]],
				"processing": true,
				"serverSide": true,
				"filter": true,
				"orderMulti": false,
				"ajax": "@Url.Action("DataTable")",
				"columns": [
					{ "data": "date" },
					{ "data": "offernumber" },
					{ "data": "employee" },
					{ "data": "building" },
					{ "data": "asset" },
					{ "data": "activity" },
					{ "data": "icon" },
					{ "data": "buttons" }
				],
				"columnDefs": [
					{
						"className": "hidden-xs",
						"targets": 2
					}, {
						"className": "hidden-xs",
						"targets": 3
					}, {
						"className": "hidden-xs",
						"targets": 4
					}, {
						"className": "hidden-xs",
						"targets": 5
					}, {
						"className": "center",
						"targets": 6
					},{
						"render": function(data, type, row) {
							var returnValue = "";
							var statusUrl = "@Url.Action("StatusUpdate")/" + row.id + '?status=@((int)PlanningStatus.Complete)';
							var modalProperties = ' data-title="' + row.offernumber + ' - ' + row.asset +'" data-url="@Url.Action("Get")/' + row.id + '" data-class="big"';
							var deleteUrl = "@Url.Action("Delete")/" + row.id;

							returnValue += '<div class="visible-md visible-lg hidden-sm hidden-xs">\n';
							returnValue += '<a href="' + statusUrl +'" class="btn btn-warning tooltips js-statuschange" data-original-title="Afronden"><i class="fa clip-checkmark-2"></i></a>\n';
							returnValue += '<a href="#" class="btn btn-teal tooltips js-popup-modal" ' + modalProperties + ' data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>\n';
							returnValue += '<a href="' + deleteUrl + '" class="btn btn-bricky tooltips js-modal-delete" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>\n';
							returnValue += '</div>\n';
							returnValue += '<div class="visible-xs visible-sm hidden-md hidden-lg">\n';
							returnValue += '<div class="btn-group">\n';
							returnValue += '<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"><i class="fa fa-cog"></i> <span class="caret"></span></a>\n';
							returnValue += '<ul role="menu" class="dropdown-menu pull-right">\n';
							returnValue += '<li role="presentation"><a href="' + statusUrl + '" class="js-statuschange"><i class="fa clip-checkmark-2"></i> Afronden</a></li>\n';
							returnValue += '<li role="presentation"><a role="menuitem" href="#" class="js-popup-modal" ' + modalProperties + '><i class="fa fa-edit"></i> Edit</a></li>\n';
							returnValue += '<li role="presentation"><a role="menuitem" href="' + deleteUrl +'" class="js-modal-delete"><i class="fa fa-times"></i> Remove</a></li>\n';
							returnValue += '</ul>\n';
							returnValue += '</div>\n';
							returnValue += '</div>\n';

							return returnValue;
						},
						className: "center",
						"targets": 7,
						"orderable": false
					}
				]
			});
		});
    </script>
}

@section PageHeader {
    <ol class="breadcrumb">
        <li><i class="clip-home"></i><a href="#">&nbsp;&nbsp;Home</a></li>
        <li class="active">Controle overzicht</li>
        @await Component.InvokeAsync("SearchBox")
    </ol>
    <div class="page-header">
        <h1> Controle <small>overzicht</small></h1>
    </div>
}
<div class="row">
    <div class="col-md-12">
        <!-- start: DYNAMIC TABLE PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-reorder"></i><div class="mobile_text">Controle</div>
                <div class="panel-tools big">
                    <a class="btn btn-lg btn-link panel-collapse collapses" href="#"> </a>
                    <a class="btn btn-lg btn-link panel-refresh js-refresh" data-id="#controle" href="#"> <i class="fa fa-refresh"></i> </a>
                    <a class="btn btn-lg btn-link panel-expand" href="#"> <i class="fa icon-resize-full"></i> </a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover table-full-width" id="controle">
                    <thead>
                        <tr>
                            <th>Datum</th>
                            <th> Offertenummer</th>
                            <th class="hidden-xs"> Werknemer</th>
                            <th class="hidden-xs"> Gebouw</th>
                            <th class="hidden-xs"> Asset</th>
                            <th class="hidden-xs"> Activiteit</th>
                            <th class="center"> Status</th>
                            <th class="center">Edit</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>