src/FusionCore/Controllers/DashboardController.cs
using AutoMapper;
using FusionCore.Core.Extensions;
using FusionCore.Models.Backend.Common;
using FusionCore.Models.Backend.Messages;
using FusionCore.Models.Backend.ToDo;
using FusionCore.Services;
using FusionCore.Services.Message;
using FusionCore.Services.ToDO;
using FusionCore.Services.User;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace FusionCore.Controllers
{
    public class DashboardController : FusionBaseController
    {
        private readonly IDashboardService _dashboardService;
        private readonly IMapper _mapper;
        private readonly IMessageService _messageService;
        private readonly IToDoService _toDoService;
        private readonly IUserService _userService;
        public DashboardController(IDashboardService dashboardService, IMapper mapper, IMessageService messageService, IToDoService toDoService, IUserService userService)
        {
            _dashboardService = dashboardService;
            _mapper = mapper;
            _messageService = messageService;
            _toDoService = toDoService;
            _userService = userService;
        }

        public IActionResult Index()
        {

            return View();
        }
        public JsonResult DataTable(RecentlyUpdatedDataTable model)
        {
            var sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][data]"]
                .FirstOrDefault();
            var sortColumnDir = Request.Query["order[0][dir]"].FirstOrDefault() ?? "";
            var searchValue = Request.Query["search[value]"].FirstOrDefault();
            int length = 5;
            if (!string.IsNullOrEmpty(Request.Query["length"]))
            {
                length = Convert.ToInt32(Request.Query["length"]);
            }
            var pageSize = model.Length;
            var pageIndex = model.Start / model.Length;

            Func<RecentlyUpdated, IComparable> orderBy;

            switch (sortColumn)
            {
                case "title":
                    orderBy = x => x.Title;
                    break;
                default:
                    orderBy = x => x.Updated;
                    //sortColumnDir = "desc";
                    break;
            }

            Expression<Func<RecentlyUpdated, bool>> predicate = null;
            if (!string.IsNullOrEmpty(searchValue))
                predicate = x => (
                        x.Title.ToLower().Contains(searchValue.ToLower()));

            var list = _dashboardService.GetRecentlyUpdated(pageIndex, length, pageSize, predicate);

            model.Data = _mapper.Map<List<RecentlyUpdated>>(list);
            model.RecordsFiltered = list.TotalCount;
            model.RecordsTotal = list.TotalCount;

            if (sortColumnDir.Equals("asc", StringComparison.InvariantCultureIgnoreCase))
            {
                model.Data = model.Data.OrderBy(orderBy).ToList();
            }
            else
            {
                model.Data = model.Data.OrderByDescending(orderBy).ToList();
            }

            return new JsonResult(model);
        }


        public IActionResult GetDashboardMessages(int pageindex)
        {
            var res = _messageService.GetDashboardChat(pageindex);
            return PartialView("GroupChatBox", res);
        }

        [HttpPost]
        public IActionResult SendMessage(GroupChatBox model)
        {
            _messageService.PostMessageinGroup(model);
            var res = _messageService.GetDashboardChat(0);
            return PartialView("GroupChatBox", res);
        }

        [HttpPost]
        public async Task<IActionResult> AddToDo(ToDoPersistModel model)
        {
            var userid = _userService.GetCurrentUserId();
            model.userId = userid;
            _toDoService.AddToDO(model);
            var res = _toDoService.GetToDO(model.userId);
            HttpContext.Session.SetComplexData("todolist", res);
            //return PartialView("ToDoList", res);
            var navtodo = res.Where(x => !x.done).ToList();
            NavigationTopModel navigationTopModel = new NavigationTopModel
            {
                AmountOfTasks = navtodo.Count(),
                todolist = navtodo
            };
            string dashboardtodo = await this.RenderViewToStringAsync("ToDoList", res);
            string navigationtoptodo = await this.RenderViewToStringAsync("_NavigationToDoList", navigationTopModel);

            return Json(new { dashboardtodo, navigationtoptodo });
        }

        public IActionResult GetToDoList()
        {
            //var userid = _userService.GetCurrentUserId();
            //var res = _toDoService.GetToDO(userid);
            var res = HttpContext.Session.GetComplexData<List<ToDoPersistModel>>("todolist");
            return PartialView("ToDoList", res);
        }

        public async Task<IActionResult> MarkasDone(int id)
        {
            var mark = _toDoService.MarkDone(id);
            var res = HttpContext.Session.GetComplexData<List<ToDoPersistModel>>("todolist");
            if (mark)
            {
                if (res != null && res.Any())
                {
                    var item = res.FirstOrDefault(x => x.Id == id);
                    if (item != null)
                    {
                        item.done = !item.done;

                        HttpContext.Session.SetComplexData("todolist", res);
                    }
                }
            }
            var navtodo = res.Where(x => !x.done).ToList();
            NavigationTopModel navigationTopModel = new NavigationTopModel
            {
                AmountOfTasks = navtodo.Count(),
                todolist = navtodo
            };
            string dashboardtodo = await this.RenderViewToStringAsync("ToDoList", res);
            string navigationtoptodo = await this.RenderViewToStringAsync("_NavigationToDoList", navigationTopModel);

            return Json(new { dashboardtodo, navigationtoptodo });
        }

        public async Task<IActionResult> DeleteToDo(int id)
        {
            var del = _toDoService.DeleteToDo(id);
            //var userid = _userService.GetCurrentUserId();
            //var res = _toDoService.GetToDO(userid);
            var res = HttpContext.Session.GetComplexData<List<ToDoPersistModel>>("todolist");
            if (del)
            {
                if (res != null && res.Any())
                {
                    var item = res.FirstOrDefault(x => x.Id == id);
                    if (item != null)
                    {
                        res.Remove(item);
                        HttpContext.Session.SetComplexData("todolist", res);
                    }
                }
            }

            //return PartialView("ToDoList", res);
            var navtodo = res.Where(x => !x.done).ToList();
            NavigationTopModel navigationTopModel = new NavigationTopModel
            {
                AmountOfTasks = navtodo.Count(),
                todolist = navtodo
            };
            string dashboardtodo = await this.RenderViewToStringAsync("ToDoList", res);
            string navigationtoptodo = await this.RenderViewToStringAsync("_NavigationToDoList", navigationTopModel);

            return Json(new { dashboardtodo, navigationtoptodo });
        }

        public IActionResult GetActiveMessageUsers()
        {
            var users = _messageService.GetActiveMessageUsers();
            return PartialView("_ProfileBarUsersList", users);
        }

        public async Task<IActionResult> GetUserMessages(int userid)
        {
            var res = _messageService.GetUserMessages(userid);
            _messageService.UpdateUserMessagesToRead(userid);
            int loginuserid = _userService.GetCurrentUserId();
            var messages = _messageService.ShowUnreadMessages(loginuserid);
            NavigationTopModel navigationTopModel = new NavigationTopModel
            {
                NewMessages = messages.Count,
                messageThreads = messages
            };
            string navmsgs = await this.RenderViewToStringAsync("_NavigationMessageList", navigationTopModel);
            string usermsgs = await this.RenderViewToStringAsync("_ProfileBarUserMessages", res);

            return Json(new { navmsgs, usermsgs });

        }
        public IActionResult UpdateUserMessagesToRead(int userid)
        {
            _messageService.UpdateUserMessagesToRead(userid);
            return Json(true);
        }

        [HttpPost]
        public IActionResult SendUserMessage(GroupChatBox model)
        {
            _messageService.PostMessageToUser(model);
            var res = _messageService.GetUserMessages(model.receiverid);
            return PartialView("_ProfileBarUserMessages", res);
        }

        public IActionResult GetUserHeaderMessages()
        {
            int userid = _userService.GetCurrentUserId();
            var messages = _messageService.ShowUnreadMessages(userid);
            NavigationTopModel navigationTopModel = new NavigationTopModel
            {
                NewMessages = messages.Count,
                messageThreads = messages
            };
            return PartialView("_NavigationMessageList", navigationTopModel);
        }

        public IActionResult DeleteMessage(int msgid,string type)
        {
            _messageService.DeleteMessage(msgid,type);
            return Json(true);
        }
    }
}

src/FusionCore/Controllers/SettingsController.cs
using AutoMapper;
using FusionCore.Core.Extensions;
using FusionCore.Data.Settings;
using FusionCore.Models.Backend.Settings;
using FusionCore.Services.Common;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FusionCore.Controllers
{
    public class SettingsController : FusionBaseController
    {
        private readonly ISettingService _settingService;
        private readonly IMapper _mapper;

        public SettingsController(
            ISettingService settingService,
            IMapper mapper)
        {
            _settingService = settingService;
            _mapper = mapper;
        }

        public IActionResult Company()
        {
            CompanySettingsModel model = _mapper.Map<CompanySettingsModel>(_settingService.LoadSetting<CompanySettings>());
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Company(CompanySettingsModel model)
        {
            if (ModelState.IsValid)
            {
                CompanySettings dbSetting = _settingService.LoadSetting<CompanySettings>();
                CompanySettings setting = _mapper.Map(model, dbSetting);
                await _settingService.SaveSetting(setting);
                AddSuccessMessage("De wijzigingen zijn opgeslagen");
                return RedirectToAction("Company");
            }

            return View(model);
        }

        public IActionResult Website()
        {
            WebsiteSettings dbSetting = _settingService.LoadSetting<WebsiteSettings>();
            WebsiteSettingsModel model = _mapper.Map<WebsiteSettingsModel>(dbSetting);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Website(WebsiteSettingsModel model)
        {
            if (ModelState.IsValid)
            {
                WebsiteSettings dbSetting = _settingService.LoadSetting<WebsiteSettings>();
                WebsiteSettings setting = _mapper.Map(model, dbSetting);
                await _settingService.SaveSetting(setting);
                AddSuccessMessage("De wijzigingen zijn opgeslagen");
                return RedirectToAction("Website");
            }

            return View(model);
        }
    }
}

src/FusionCore/Views/Settings/Company.cshtml
@using FusionCore.Models.Backend.Settings
@model CompanySettingsModel
@{
	ViewData["Title"] = "Bedrijfsinformatie";
}
@section PageHeader
	{
	<ol class="breadcrumb">
		<li><i class="clip-home"></i><a asp-controller="Dashboard" asp-action="Index">&nbsp;Home</a></li>
		<li class="active">Bedrijsinformatie edit</li>
		@await Component.InvokeAsync("SearchBox")
	</ol>
	<div class="page-header">
		<h1>Bedrijsinformatie <small>edit</small></h1>
	</div>
}

<form asp-action="Company" role="form">
	<div class="row">
		<div class="col-sm-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-external fa-reorder"></i><div class="mobile_text">Algemene informatie</div>
					<div class="panel-tools big">

						<a class="btn btn-lg btn-link panel-collapse collapses" href="#">
						</a>

						<a class="btn btn-lg btn-link panel-expand" href="#">
							<i class="fa icon-resize-full"></i>
						</a>
					</div>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-12">
							<div id="panel_edit_account" class="tab-pane">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label class="control-label">Bedrijfsnaam</label>
											<input asp-for="CompanyName" type="text" placeholder="Novi Media" class="form-control" />
										</div>
										<div class="space_white"></div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-12">
												<h4>Contactpersoon</h4>
												<hr />
												<div class="form-group">
													<label class="control-label">Naam</label>
													<input asp-for="ContactFirstName" type="text" placeholder="Peter" class="form-control" />
												</div>
												<div class="form-group">
													<label class="control-label">Tussenvoegsel</label>
													<input asp-for="ContactMiddleName" type="text" placeholder="de" class="form-control" />
												</div>
												<div class="form-group">
													<label class="control-label">Achternaam</label>
													<input asp-for="ContactLastName" type="text" placeholder="Clark" class="form-control" />
												</div>
												<h4 class="italic">Contact gegevens</h4>
												<hr />
												<div class="form-group">
													<label class="control-label">Telefoon</label>
													<span class="input-icon">
														<input asp-for="ContactPhonenumber" type="text" placeholder="03058896635" />
														<i class="fa fa-phone-square"></i>
													</span>
												</div>
												<div class="form-group">
													<label class="control-label">Mobiel</label>
													<span class="input-icon">
														<input asp-for="ContactMobilenumber" type="text" placeholder="06255899663" class="form-control" />
														<i class="fa clip-mobile"></i>
													</span>
												</div>
												<div class="form-group">
													<label class="control-label">Email</label>
													<span class="input-icon">
														<input asp-for="ContactEmail" type="text" placeholder="martijn@novimedia.nl" class="form-control">
														<i class="fa fa-envelope-square"></i>
													</span>
												</div>
											</div>
										</div>
									</div>
									<div class="col-md-6">
										<div class="row">
											<div class="col-md-12">
												<h4>Adresgegevens</h4>
												<hr />
												<div class="form-group">
													<label class="control-label">Adres</label>
													<input asp-for="AddressLine1" type="text" placeholder="Duizendknooplaan 19" class="form-control" />
												</div>
												<div class="row">
													<div class="col-md-4">
														<div class="form-group">
															<label class="control-label">Postcode</label>
															<input asp-for="AddressPostalCode" class="form-control" placeholder="1234AB" type="text" />
														</div>
													</div>
													<div class="col-md-8">
														<div class="form-group">
															<label class="control-label">Woonplaats</label>
															<input asp-for="AddressCity" class="form-control tooltips" placeholder="Utrecht" type="text" />
														</div>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label">Land</label>
													<input asp-for="AddressCountry" type="text" placeholder="the Netherlands" class="form-control" />
												</div>
												<h4 class="italic">Overige gegevens</h4>
												<hr />
												<label class="control-label">Website</label>
												<span class="input-icon">
													<input asp-for="OtherWebsite" type="text" placeholder="www.novimedia.nl" class="form-control">
													<i class="fa clip-globe"></i>
												</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-external fa-reorder"></i><div class="mobile_text">Pagina instellingen</div>
					<div class="panel-tools big">
						<a class="btn btn-lg btn-link panel-collapse collapses" href="#">
						</a>
						<a class="btn btn-lg btn-link panel-expand" href="#">
							<i class="fa icon-resize-full"></i>
						</a>
					</div>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-12">
							<button class="btn btn-teal btn-lg btn-block" type="submit">Update <i class="fa fa-arrow-circle-right"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

src/FusionCore/Views/Settings/Website.cshtml
@model FusionCore.Models.Backend.Settings.WebsiteSettingsModel
@{
    ViewData["Title"] = "Website gegevens";
}
@section Head
	{
    <link href="~/assets/libs/select2/dist/css/select2.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/datatables/media/css/dataTables.bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/bootstrap-social/bootstrap-social.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/assets/libs/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" asp-append-version="true" />

}
@section Scripts
	{
    <script src="~/assets/libs/moment/min/moment.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-maxlength/src/bootstrap-maxlength.js" asp-append-version="true"></script>
    <script src="~/assets/libs/autosize/dist/autosize.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/select2/dist/js/select2.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.maskedinput/dist/jquery.maskedinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery-maskmoney/dist/jquery.maskMoney.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-daterangepicker/daterangepicker.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.js" asp-append-version="true"></script>
    <script src="~/assets/libs/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.tagsinput/src/jquery.tagsinput.js" asp-append-version="true"></script>
    <script src="~/assets/libs/summernote/dist/summernote.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/ckeditor/ckeditor.js" asp-append-version="true"></script>
    <script src="~/assets/libs/ckeditor/adapters/jquery.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery.pulsate/jquery.pulsate.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/bootbox.js/bootbox.js" asp-append-version="true"></script>
    <script src="~/assets/libs/jquery-mockjax/dist/jquery.mockjax.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/datatables/media/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/assets/libs/datatables/media/js/dataTables.bootstrap.js" asp-append-version="true"></script>
    <script src="~/assets/js/table-data.js" asp-append-version="true"></script>
    <script src="~/assets/js/pages-user-profile.js" asp-append-version="true"></script>
    <script src="~/assets/js/form-elements.js" asp-append-version="true"></script>
}
@section PageHeader
	{
    <ol class="breadcrumb">
        <li><i class="clip-home"></i><a asp-controller="Dashboard" asp-action="Index">&nbsp;Home</a></li>
        <li class="active">Website gegevens edit</li>
        @await Component.InvokeAsync("SearchBox")
    </ol>
    <div class="page-header">
        <h1>Website gegevens <small>edit</small></h1>
    </div>
}

<form asp-action="Website">
    <div class="row">
        <div class="col-sm-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external fa-reorder"></i><div class="mobile_text">Google Analytics</div>
                    <div class="panel-tools big">
                        <a class="btn btn-lg btn-link panel-collapse collapses" href="#">
                        </a>
                        <a class="btn btn-lg btn-link panel-expand" href="#">
                            <i class="fa icon-resize-full"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div id="panel_edit_account" class="tab-pane">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-10">
                                                <div class="form-group">
                                                    <span class="input-icon">
                                                        <input asp-for="GoogleAnalyticsCode" class="form-control" type="text" placeholder="Analytics code Voorbeeld: UA-34890XXX-X" />
                                                        <i class="fa clip-stats"></i>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="col-md-2">
                                                <a class="btn btn-green btn-block" href="https://www.google.com/analytics/" target="_blank">Link <i class="fa fa-arrow-circle-right"></i></a>
                                            </div>
                                        </div>
                                        <hr style="margin-top:7px;" />
                                        <div class="row">
                                            <div class="col-md-12">
                                                <h3>Social Media</h3>
                                                <hr />
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="control-label">Twitter</label>
                                                    <span class="input-icon">
                                                        <input asp-for="TwitterCode" class="form-control" type="text" placeholder="Twitter code" />
                                                        <i class="clip-twitter"></i>
                                                    </span>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">Facebook</label>
                                                    <span class="input-icon">
                                                        <input asp-for="FacebookCode" class="form-control" type="text" placeholder="Facebook code" />
                                                        <i class="clip-facebook"></i>
                                                    </span>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">Google Plus</label>
                                                    <span class="input-icon">
                                                        <input asp-for="GooglePlusCode" class="form-control" type="text" placeholder="Google plus code" />
                                                        <i class="clip-google-plus"></i>
                                                    </span>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label">Instagram</label>
                                                    <span class="input-icon">
                                                        <input asp-for="InstagramCode" class="form-control" type="text" placeholder="Instagram code" />
                                                        <i class="fa fa-instagram"></i>
                                                    </span>
                                                </div>

                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="control-label">Linkedin</label>
                                                    <span class="input-icon">
                                                        <input asp-for="LinkedInCode" class="form-control" type="text" placeholder="Linkedin code" />
                                                        <i class="clip-linkedin"></i>
                                                    </span>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">Skype</label>
                                                    <span class="input-icon">
                                                        <input asp-for="SkypeCode" class="form-control" type="text" placeholder="Skype code" />
                                                        <i class="clip-skype"></i>
                                                    </span>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label">Whatsapp</label>
                                                    <span class="input-icon">
                                                        <input asp-for="WhatsappCode" class="form-control" type="text" placeholder="Whatsapp code" />
                                                        <i class="fa fa-whatsapp"></i>
                                                    </span>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label">Youtube</label>
                                                    <span class="input-icon">
                                                        <input asp-for="YoutubeCode" class="form-control" type="text" placeholder="Youtube code" />
                                                        <i class="fa fa-youtube"></i>
                                                    </span>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external fa-reorder"></i><div class="mobile_text">Pagina instellingen</div>
                    <div class="panel-tools big">
                        <a class="btn btn-lg btn-link panel-collapse collapses" href="#">
                        </a>
                        <a class="btn btn-lg btn-link panel-expand" href="#">
                            <i class="fa icon-resize-full"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <button class="btn btn-teal btn-lg btn-block" type="submit">Update <i class="fa fa-arrow-circle-right"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>