src/Modules/FusionCore.Modules.InstallationManager/Controllers/AssetController.cs
using AutoMapper;
using FusionCore.Core.Enums;
using FusionCore.Core.Exceptions;
using FusionCore.Core.Extensions;
using FusionCore.Core.Helpers;
using FusionCore.Modules.InstallationManager.Data.Entities;
using FusionCore.Modules.InstallationManager.Data.Enums;
using FusionCore.Modules.InstallationManager.Interfaces;
using FusionCore.Modules.InstallationManager.Models;
using FusionCore.Services.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace FusionCore.Modules.InstallationManager.Controllers
{
    [Area("InstallationManager")]
    public class AssetController : FusionBaseController
    {
        private readonly IAssetService _assetService;
        private readonly IBuildingService _buildingService;
        private readonly IActivityService _activityService;
        private readonly IPlanningService _planningService;
        private readonly IAssetFileService _assetFileService;
        private readonly IMapper _mapper;

        public AssetController(
            IAssetService assetService,
            IBuildingService buildingService,
            IActivityService activityService,
            IMapper mapper,
            IPlanningService planningService,
            IAssetFileService assetFileService)
        {
            _assetService = assetService;
            _buildingService = buildingService;
            _activityService = activityService;
            _mapper = mapper;
            _planningService = planningService;
            _assetFileService = assetFileService;
        }

        public IActionResult Index(int? buildingLocationId, int? id)
        {
            AssetIndexViewModel model = new AssetIndexViewModel
            {
                BuildingLocationId = buildingLocationId,
                Id = id
            };
            return View(model);
        }

        public JsonResult DataTable(AssetDataTable model)
        {
            string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][data]"]
                .FirstOrDefault();
            string sortColumnDir = Request.Query["order[0][dir]"].FirstOrDefault() ?? "";
            string searchValue = Request.Query["search[value]"].FirstOrDefault();

            int pageSize = model.Length;
            int pageIndex = model.Start / model.Length;

            Expression<Func<Asset, IComparable>> orderBy;

            switch (sortColumn)
            {
                case "name":
                    orderBy = x => x.Name;
                    break;
                case "buildingName":
                    orderBy = x => x.Building.Name;
                    break;
                case "locationName":
                    orderBy = x => x.BuildingLocation.Name;
                    break;
                default:
                    orderBy = x => x.UpdatedOnUtc;
                    sortColumnDir = "desc";
                    break;
            }

            Expression<Func<Asset, bool>> predicate = null;
            if (!string.IsNullOrEmpty(searchValue))
                predicate = x =>
                        x.Name.ToLower().Contains(searchValue.ToLower())
                        || x.AssetType.Name.ToLower().Contains(searchValue.ToLower())
                        || x.Building.Name.ToLower().Contains(searchValue.ToLower())
                        || x.BuildingLocation.Name.ToLower().Contains(searchValue.ToLower())
                    ;

            FusionCore.Models.Common.IPagedList<Asset> assets = _assetService.GetAllAssets(
                predicate,
                orderBy,
                sortColumnDir.Equals("asc", StringComparison.InvariantCultureIgnoreCase),
                pageIndex,
                pageSize);

            model.Data = _mapper.Map<List<AssetDataRow>>(assets);
            model.RecordsFiltered = assets.TotalCount;
            model.RecordsTotal = assets.TotalCount;
            return new JsonResult(model);
        }

        public IActionResult Get(int? id, int buildingLocationId = 0)
        {
            AssetPersistModel model = id.HasValue ? _mapper.Map<AssetPersistModel>(_assetService.GetAsset(id.Value)) : new AssetPersistModel();

            IEnumerable<BuildingLocation> buildingLocations = _buildingService.GetAllBuildings<Building>(loadLocations: true)
                .SelectMany(x => x.BuildingLocations);
            buildingLocationId = model.BuildingLocationId ?? buildingLocationId;
            IList<AssetType> assetTypes = _activityService.GetAssetTypes();

            List<SelectListItem> availableLocations = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = "",
                    Text = "Selecteer"
                }
            };
            availableLocations.AddRange(buildingLocations.OrderBy(x => x.Building.Name).ThenBy(x => x.Name).Select(x => new SelectListItem
            {
                Selected = x.Id == buildingLocationId,
                Text = $"{x.Building.Name} - {x.Name}",
                Value = x.Id.ToString()
            }).ToList());

            List<SelectListItem> availableTypes = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = "",
                    Text = "Selecteer"
                }
            };
            availableTypes.AddRange(assetTypes.OrderBy(x => x.Name).Select(x => new SelectListItem
            {
                Selected = x.Id == model.AssetTypeId,
                Text = $"{x.Name}",
                Value = x.Id.ToString()
            }).ToList());

            model.AvailableLocations = availableLocations;
            model.AvailableTypes = availableTypes;
            model.Activities = id.HasValue ? _assetService.GetAllAssetActivities(id.Value, null, x => x.SortOrder).OrderBy(x => x.Name).ToList() : new List<AssetActivity>();
            return View(model);
        }

        [HttpPost]
        public IActionResult Persist(AssetPersistModel model)
        {
            if (ModelState.IsValid)
            {
                BuildingLocation location = _buildingService.GetBuildingLocation(model.BuildingLocationId.GetValueOrDefault());
                model.BuildingId = location?.BuildingId;
                return Json(_assetService.PersistAsset(model));
            }

            return Json(false);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _assetService.DeleteAsset(id);

            return RedirectToAction("Index");
        }

        public JsonResult DataTableBuildingAssetDynamicFields(AssetDynamicFieldDataTable model)
        {
            int pageSize = model.Length;
            int pageIndex = model.Start / model.Length;

            FusionCore.Models.Common.IPagedList<AssetDynamicField> assets = _assetService.GetAllAssetDynamicFields(
                model.AssetId,
                null,
                x => x.SortOrder,
                true,
                pageIndex,
                pageSize);

            model.Data = _mapper.Map<List<AssetDynamicFieldDataRow>>(assets);
            model.RecordsFiltered = assets.TotalCount;
            model.RecordsTotal = assets.TotalCount;
            return new JsonResult(model);
        }

        public async Task<IActionResult> DeleteAssetDynamicField(int id)
        {
            await _assetService.DeleteAssetDynamicField(id);

            return Json(true);
        }

        public IActionResult PersistAssetDynamicField(int? id, int assetId, string name, string value)
        {
            if (id == 0) id = null;
            AssetDynamicFieldPersistModel saveModel = new AssetDynamicFieldPersistModel
            {
                AssetId = assetId,
                Id = id,
                Name = name,
                Value = value
            };
            return Json(_assetService.PersistAssetDynamicField(saveModel));
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult PersistAssetActivityField(int? pk, string value, int assetActivityId)
        {
            if (pk == 0) pk = null;
            return Json(_assetService.PersistAssetActivityField(new AssetActivityFieldNamePersistModel
            {
                Id = pk,
                Name = value,
                AssetActivityId = assetActivityId
            }).HasValue);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult PersistAssetActivityFieldLatestValue(int id, int assetActivityId, string value)
        {
            return Json(_assetService.PersistAssetActivityField(new AssetActivityFieldValuePersistModel
            {
                Id = id,
                LatestValue = value,
                AssetActivityId = assetActivityId
            }).HasValue);
        }

        public async Task<IActionResult> DeleteAssetActivityField(int id)
        {
            await _assetService.DeleteAssetActivityField(id);
            return Json(true);
        }

        [HttpPost]
        public IActionResult SetActiveAssetActivity(int id)
        {
            AssetActivity assetActivity = _assetService.GetAssetActivity(id);
            if (assetActivity != null)
            {
                assetActivity.Active = !assetActivity.Active;
                _assetService.UpdateAssetActivity(assetActivity);
            }

            return Json(true);
        }

        public IActionResult LoadActivities(int id)
        {
            return View(_assetService.GetAllAssetActivities(id, null, x => x.SortOrder).ToList());
        }

        public IActionResult AddActivity(int assetId)
        {
            AssetActivityPersistModel model = new AssetActivityPersistModel

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Asset/AddActivity.cshtml
@model FusionCore.Modules.InstallationManager.Models.AssetActivityPersistModel
@{
	Layout = null;
}
<form asp-action="AddActivity">
	<input type="hidden" asp-for="AssetId" />
	<div class="modal-body">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="control-label">Activiteit</label>
					<input type="text" placeholder="Activiteit name" class="form-control" asp-for="Name" />
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Terug</button>
		<button type="submit" class="btn btn-primary">Opslaan</button>
	</div>
</form>

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Asset/AddActivityField.cshtml
@using FusionCore.Modules.InstallationManager.Data.Enums
@using FusionCore.Core.Extensions
@model FusionCore.Modules.InstallationManager.Models.AssetActivityFieldPersistModel
@{
	Layout = null;
}
<form asp-action="AddActivityField">
	<input type="hidden" asp-for="AssetActivityId" />
	<div class="modal-body">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="control-label">Werkbon item</label>
					<span class="input-icon dropdown_space_page">
						<select asp-for="DynamicFieldTypeId" class="form-control">
							<option value="">Selecteer een item</option>
							@{ 
								var values = Enum.GetValues(typeof(DynamicFieldType)).Cast<DynamicFieldType>().OrderBy(x => x.GetStringValue());
								foreach(var item in values.Where(x => x != DynamicFieldType.File && x != DynamicFieldType.Image))
								{
									<option value="@((int)item)">@item.GetStringValue()</option>		
								}
							}
						</select>
						<i class="fa fa-wrench"></i>
					</span>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Terug</button>
		<button type="submit" class="btn btn-primary">Opslaan</button>
	</div>
</form>

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Asset/ImageList.cshtml
@model System.Collections.Generic.List<FusionCore.Modules.InstallationManager.Data.Entities.AssetFile>

@{
	Layout = null;
	var groups = Model.GroupBy(x => x.CreatedOnUtc.Date);
}
@foreach (var group in groups)
{
	var images = Model.Where(x => x.CreatedOnUtc.Date == group.Key).ToList();
	<div class="col-sm-12">
		<div class="panel-group margin-bottom-small" id="acc@(group.Key.Ticks)">
			<div class="panel panel-default">
				<div class="panel-heading padding-left-small">
					<a data-toggle="collapse" data-parent="#acc@(group.Key.Ticks)" href="#@group.Key.Ticks" class="link-collapse text-resp assets"><i class="fa fa-arrow-down"></i> @group.Key.ToString("dd-MM-yyyy")</a>
					<a href="@Url.Action("DeleteFile", new {date = group.Key.Date})" data-function="LoadImages" class="js-modal-delete-ajax btn btn-bricky tooltips pull-right" style="margin-right: -14px; margin-top: -9px;">
						<i class="fa fa-times fa fa-white"></i>
					</a>
				</div>
				<div id="@group.Key.Ticks" class="panel-collapse collapse">
					<div class="panel-body">
						<div class="row">
							@foreach (var image in images)
							{
								<div class="col-md-3 col-sm-4 gallery-img">
									<div class="wrap-image">
										<a class="group1" href="@Url.Action("DownloadFile", new {image.Id})" title="Clip-One Business Card">
											<img src="@Url.Action("Image", "Asset", new {id = image.Id})" alt="@image.Id" class="img-responsive">
										</a>
										<div class="tools tools-bottom">
											<a href="@Url.Action("DeleteFile", new {image.Id})" data-function="LoadImages" class="js-modal-delete-ajax">
												<i class="clip-close-2 fa-3x"></i>
											</a>
										</div>
									</div>
								</div>
							}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Asset/Index.cshtml
@model FusionCore.Modules.InstallationManager.Models.AssetIndexViewModel
@{
	ViewData["Title"] = "Installatie asset overzicht";
	Layout = "~/Views/Shared/_layout.cshtml";
}

@section Head {
	<link href="~/assets/libs/select2/dist/css/select2.min.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/datatables/media/css/dataTables.bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/summernote/dist/summernote.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/bootstrap-social/bootstrap-social.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/x-editable/dist/inputs-ext/address/address.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/assets/libs/x-editable/dist/inputs-ext/typeaheadjs/lib/typeahead.js-bootstrap.css" rel="stylesheet" asp-append-version="true" />
	<style>
		
		.af_range.af_range_ok {
			background:#92d050;
			color:#000000;    
		}
		.af_range.af_range_outside {
			background:#ffc000;
			color:#000000;    
		}

		.af_hv.af_hv_1,
		.af_hv.af_hv_2 {
			background: rgb(83, 142, 213);
			color:#000000;    
		}

		.af_hv.af_hv_3,
		.af_hv.af_hv_4 {
			background:rgb(146, 208, 80);
			color:#000000;    
		}

		.af_hv.af_hv_5 {
    
			background:rgb(255, 192, 0);
			color:#000000;    
		}

		.af_hv.af_hv_6 {
			background: rgb(255, 0, 0);
			color:#000000;    
		}

		.af_tvrtav.af_tvrtav_1 {
			background:rgb(146, 208, 80);
			color:#000000;    
		}
    

		.af_tvrtav.af_tvrtav_2 {
			background:rgb(255, 192, 0);
			color:#000000;    
		}
    

		.af_tvrtav.af_tvrtav_3 {
			background: rgb(255, 0, 0);
			color:#000000;    
		}
	</style>
}

@section Scripts {

	<script src="~/assets/libs/moment/min/moment.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-maxlength/src/bootstrap-maxlength.js" asp-append-version="true"></script>
	<script src="~/assets/libs/autosize/dist/autosize.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/select2/dist/js/select2.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/jquery.maskedinput/dist/jquery.maskedinput.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/jquery-maskmoney/dist/jquery.maskMoney.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-daterangepicker/daterangepicker.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.js" asp-append-version="true"></script>
	<script src="~/assets/libs/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/jquery.tagsinput/src/jquery.tagsinput.js" asp-append-version="true"></script>
	<script src="~/assets/libs/summernote/dist/summernote.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/ckeditor/ckeditor.js" asp-append-version="true"></script>
	<script src="~/assets/libs/ckeditor/adapters/jquery.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/jquery.pulsate/jquery.pulsate.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootstrap-fileinput/js/fileinput.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/bootbox.js/bootbox.js" asp-append-version="true"></script>
	<script src="~/assets/libs/jquery-mockjax/dist/jquery.mockjax.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/datatables/media/js/jquery.dataTables.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/datatables/media/js/dataTables.bootstrap.js" asp-append-version="true"></script>
	<script src="~/assets/libs/Nestable/dist/js/jquery.nestable.js" asp-append-version="true"></script>

	<script src="~/assets/libs/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js" asp-append-version="true"></script>
	<script src="~/assets/libs/x-editable/dist/inputs-ext/typeaheadjs/typeaheadjs.js" asp-append-version="true"></script>
	<script src="~/assets/libs/x-editable/dist/inputs-ext/typeaheadjs/lib/typeahead.js" asp-append-version="true"></script>
	<script src="~/assets/libs/x-editable/dist/inputs-ext/address/address.js" asp-append-version="true"></script>
	<script src="~/assets/js/pages-user-profile.js" asp-append-version="true"></script>
	<script src="~/assets/js/form-elements.js" asp-append-version="true"></script>
	<script>
		jQuery(document).ready(function() {
			@if (Model.Id.HasValue)
			{
				<text>PreLoadItem();</text>
			}
			$("body").on('click', '#js-submitbutton', function() {
				$("#assetGetForm").submit();
			});
			$("body").on('click',
				'.js-activitydelete',
				function(e) {
					e.preventDefault();
					$this = $(this);
					bootbox.confirm("Weet u het zeker?",
						function(result) {
							if (result) {
								$.ajax($this.data('url')).then(function(data) {
									if (data) {
										Main.runLoadContent();
									} else {

										Main.AddAlert(
											"Verwijderen is niet mogelijk, omdat er planningen aan gekoppeld zijn",
											"#panel_tab_algemeen #activities");
									}
								});
							}
						});

					return false;
				});

			$("body").on('change', ".af_range", function () {
				var val = parseInt($(this).val());
				var parent = $(this).parent().parent();
				var minVal = parseInt(parent.find(".one").val());
				var maxVal = parseInt(parent.find(".two").val());
				$(this).removeClass("af_range_ok");
				$(this).removeClass("af_range_outside");
				if (minVal <= val && maxVal >= val) {
					$(this).addClass("af_range_ok");
				} else {
					$(this).addClass("af_range_outside");
				}
			}).trigger('change');

			$('body').on('change',
				'.af_hv',
				function() {
					$(this).removeClass("af_hv_1");
					$(this).removeClass("af_hv_2");
					$(this).removeClass("af_hv_3");
					$(this).removeClass("af_hv_4");
					$(this).removeClass("af_hv_5");
					$(this).removeClass("af_hv_6");
					var val = $(this).val();
					if (val === "") return;

					if (val > 6) val = 6;
					if (val < 1) val = 1;

					$(this).addClass("af_hv_" + val);
				}).trigger('change');


		$('#asset').DataTable({
			'stateSave': true,
			"processing": true,
			"serverSide": true,
			"filter": true,
			"orderMulti": false,
			"ajax": "@Url.Action("DataTable")",
			"columns": [
				{ "data": "name" },
				{ "data": "buildingName" },
				{ "data": "locationName" },
				{ "data": "buttons" }
			],
			"columnDefs": [
				{
					"className": "hidden-xs",
					"targets": 1
				}, {
					"className": "hidden-xs",
					"targets": 2
				}, {
					"render": function(data, type, row) {
						@{
							var editUrl = Url.Action("Get");
						}
						var returnValue = "";
						var modalProperties = " data-title=\"" +
							row.name +
							"\" data-url=\"@editUrl/" +
							row.id +
							"\" data-class=\"super\"";
						var deleteUrl = "@Url.Action("Delete")/" + row.id;
						returnValue += "<div class=\"visible-md visible-lg hidden-sm hidden-xs\">\n";
						returnValue +=
							"<a href=\"#panel-gebruiker-edit\" class=\"btn btn-teal tooltips js-popup-modal\" " +
							modalProperties +
							" data-placement=\"top\" data-original-title=\"Edit\"><i class=\"fa fa-edit\"></i></a>\n";
						returnValue +=
							"<a href=\"" +
							deleteUrl +
							"\" class=\"btn btn-bricky tooltips js-modal-delete\" data-placement=\"top\" data-original-title=\"Remove\"><i class=\"fa fa-times fa fa-white\"></i></a>\n";
						returnValue += "</div>\n";
						returnValue += "<div class=\"visible-xs visible-sm hidden-md hidden-lg\">\n";
						returnValue += "<div class=\"btn-group\">\n";
						returnValue +=
							"<a class=\"btn btn-primary dropdown-toggle btn-sm\" data-toggle=\"dropdown\" href=\"#\"><i class=\"fa fa-cog\"></i> <span class=\"caret\"></span></a>\n";
						returnValue += "<ul role=\"menu\" class=\"dropdown-menu pull-right\">\n";
						returnValue +=
							"<li role=\"presentation\"><a role=\"menuitem\" href=\"#\" class=\"js-popup-modal\" " +
							modalProperties +
							"><i class=\"fa fa-edit\"></i> Edit</a></li>\n";
						returnValue +=
							"<li role=\"presentation\"><a role=\"menuitem\" href=\"" +
							deleteUrl +
							"\" class=\"js-modal-delete\"><i class=\"fa fa-times\"></i> Remove</a></li>\n";
						returnValue += "</ul>\n";
						returnValue += "</div>\n";
						returnValue += "</div>\n";

						return returnValue;
					},
					className: "center",
					"targets": 3,
					"orderable": false
				}
			]
		});
	});
		@if (Model.Id.HasValue)
		{
				<text>
				function PreLoadItem() {
					Modals.CreateModal('Asset', '@Url.Action("Get")/@Model.Id.Value', 'super', function() {

						try {
							$("#asset").dataTable().api().ajax.reload(null, false);
						} catch (err) {
							//ignored
						}

					});
				}
				</text>
		}
	</script>
}

@section PageHeader {
	<ol class="breadcrumb">
		<li>
			<i class="clip-home"></i><a asp-controller="Dashboard" asp-action="Index">&nbsp;Home</a>
		</li>
		<li class="active">Gebouwen & Locaties overzicht</li>
		@await Component.InvokeAsync("SearchBox")
	</ol>
	<div class="page-header">
		<span class="pull-right">
			<a class="btn btn-primary js-popup-modal js-new-button" data-class="super" data-title="Nieuw gebouw" data-url="@Url.Action("Get")?buildingLocationId=@Model.BuildingLocationId"><i class="fa fa-plus"></i> toevoegen</a>
		</span>
		<h1> Asset <small>overzicht</small></h1>
	</div>

}

<div class="row">
	<div class="col-md-12">
		<!-- start: DYNAMIC TABLE PANEL -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-reorder"></i>
				<div class="mobile_text">Assets</div>
				<div class="panel-tools big">
					<a class="btn btn-lg btn-link panel-collapse collapses" href="#"> </a>

					<a class="btn btn-lg btn-link panel-refresh js-refresh" data-id="#asset" href="#"><i class="fa fa-refresh"></i></a>
					<a class="btn btn-lg btn-link panel-expand" href="#">
						<i class="fa icon-resize-full"></i>
					</a>
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-striped table-bordered table-hover table-full-width" id="asset">
					<thead>
						<tr>
							<th>Naam</th>
							<th class="hidden-xs"> Gebouw</th>
							<th class="hidden-xs"> Locatie</th>
							<th class="center">Edit</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>

src/Modules/FusionCore.Modules.InstallationManager/Areas/InstallationManager/Views/Asset/LoadActivities.cshtml
@model System.Collections.Generic.List<FusionCore.Modules.InstallationManager.Data.Entities.AssetActivity>

@{
	Layout = null;
}
<div class="panel-group" id="accordion">
	@foreach (var activity in Model)
	{
		<div class="panel panel-default">
			<div class="panel-heading padding-left-small">
				<a data-toggle="collapse" data-parent="#accordion" href="#activity@(activity.Id)" class="link-collapse text-resp assets"><i class="fa fa-arrow-down"></i> @activity.Name</a>
				<a href="#" data-url="@Url.Action("DeleteActivity")?activity=@activity.Id" class="btn btn-bricky tooltips pull-right js-activitydelete" style="margin-top: -9px; margin-right: -14px;" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
				<a href="@Url.Action("Index", "Planning")?activity=@activity.Id" target="_blank" data-toggle="modal" class="btn btn-primary tooltips pull-right" style="margin-right: 5px; margin-top: -9px;" data-placement="top" data-original-title="Inplannen">
					<i class="fa clip-calendar-3 fa fa-white"></i>
				</a>
				<a class="btn btn-primary btn-xs pull-right js-popup-modal" href="#" style="margin-top: -3px; margin-right: 8px;" data-title="Werkbon item toevoegen" data-url="@Url.Action("AddActivityField", new {assetActivityId = activity.Id})" data-class="" data-reload-content="true"><i class="fa fa-plus"></i> toevoegen</a>
				<div class="pull-right" style="margin-top: -7px; margin-right: 7px;">
					<input asp-for="@activity.Active" type="checkbox" data-toggle="toggle" data-onstyle="teal" data-size="small" data-url="@Url.Action("SetActiveAssetActivity", new {id = activity.Id})" class="js-post-remove" data-element="">
				</div>
			</div>
			<div id="activity@(activity.Id)" class="panel-collapse collapse">
				<div class="panel-body">
					<div class="col-md-12">
						<div class="form-group">
							<div class="row">
								@await Component.InvokeAsync("ActivityFields", new { activityId = activity.Id })
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	}
</div>
<script>
	$(function() {
		$(".af_hv").each(function (i, elm) {
			$(this).change();
		});

		$(".af_range").each(function (i, elm) {
			$(this).change();
		});
	});
</script>